# Generated by Django 6.1 on 2026-08-08 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused', models.BooleanField(default=False, help_text='Master kill switch. While on, no run may contact anyone.')),
                ('hard_daily_ceiling', models.PositiveIntegerField(default=200, help_text='Absolute cap across all profiles, whatever a profile asks for.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global settings',
                'verbose_name_plural': 'Global settings',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(help_text='Placeholders: {name}, {first_name}, {id}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('pass_id', models.CharField(help_text='Placement id from the portal URL, e.g. 82413.', max_length=32)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Search filters as {field: value}, matching the portal form.')),
                ('per_run_cap', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)])),
                ('per_day_cap', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_delay_s', models.PositiveIntegerField(default=8)),
                ('max_delay_s', models.PositiveIntegerField(default=20)),
                ('max_pages', models.PositiveIntegerField(default=20, help_text='Stop paginating after this many result pages.')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='esc.messagetemplate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped'), ('NEEDS_LOGIN', 'Needs login')], default='QUEUED', max_length=16)),
                ('dry_run', models.BooleanField(default=True)),
                ('stop_requested', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('found_count', models.PositiveIntegerField(default=0)),
                ('contacted_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('search_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='esc.searchprofile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRY_RUN', 'Dry run (nothing sent)'), ('SENT', 'Sent'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach', to='esc.candidate')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='esc.messagetemplate')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach', to='esc.run')),
                ('search_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach', to='esc.searchprofile')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('search_profile', 'candidate'), name='unique_outreach_per_profile_candidate')],
            },
        ),
    ]
