# Generated by Django 6.1 on 2026-09-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='status',
            field=models.CharField(choices=[('DRY_RUN', 'Dry run (nothing sent)'), ('SENDING', 'Sending (unconfirmed)'), ('SENT', 'Sent'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=12),
        ),
    ]
