import json

from django import forms

from .models import GlobalSettings, MessageTemplate, SearchProfile


class SearchProfileForm(forms.ModelForm):
    """Everything about a profile except its filters.

    Filters are edited by a separate, dynamically built form because their
    fields come from the portal, not from this model.
    """

    class Meta:
        model = SearchProfile
        fields = [
            'name', 'pass_id', 'template', 'per_run_cap', 'per_day_cap',
            'min_delay_s', 'max_delay_s', 'max_pages', 'enabled',
        ]
        widgets = {
            'pass_id': forms.TextInput(attrs={'placeholder': '82413'}),
        }

    def clean(self):
        cleaned = super().clean()
        lo, hi = cleaned.get('min_delay_s'), cleaned.get('max_delay_s')
        if lo is not None and hi is not None and lo > hi:
            self.add_error('max_delay_s', 'Maximum delay must not be below the minimum.')

        ceiling = GlobalSettings.load().hard_daily_ceiling
        per_day = cleaned.get('per_day_cap')
        if per_day and per_day > ceiling:
            self.add_error(
                'per_day_cap',
                f'The global hard ceiling is {ceiling}. Raise it in Settings first '
                f'if you really mean to go above it.',
            )
        return cleaned


def _field_for(entry):
    """One Django field mirroring a portal search field.

    Portal-required fields (start/end date, duration, activity topics) are
    required here too, so the UI refuses to save a profile the portal would
    reject at submit time.
    """
    label = entry.get('label') or entry['name']
    kind = entry.get('type', 'text')
    choices = entry.get('choices')
    required = bool(entry.get('required'))

    if choices:
        opts = [(c['value'], c['label']) for c in choices]
        if not required:
            opts = [('', '— any —')] + opts
        return forms.ChoiceField(label=label, choices=opts, required=required)
    if kind == 'checkbox':
        return forms.BooleanField(label=label, required=False)
    if kind in ('number', 'range'):
        return forms.IntegerField(label=label, required=required, min_value=0)
    if kind == 'date':
        return forms.DateField(
            label=label, required=required,
            widget=forms.DateInput(attrs={'type': 'date'}),
        )
    return forms.CharField(label=label, required=required)


def build_filter_form(schema, data=None, initial=None, funding_field=None):
    """Build a form whose fields mirror the portal's own search filters.

    Rendering from the schema generated by ``esc_inspect`` keeps this UI from
    drifting away from the real form — there is no second hand-maintained list
    of field names to fall out of date. Field keys are the portal's own names
    (``period[start]``, ``projects[]``, …) so the stored filters feed straight
    back to the wizard driver.
    """
    fields = {}
    if funding_field and funding_field.get('name'):
        fields[funding_field['name']] = _field_for({**funding_field, 'required': True})
    for entry in schema:
        fields[entry['name']] = _field_for(entry)

    form_class = type('FilterForm', (forms.Form,), fields)
    return form_class(data=data, initial=initial or {})


def filters_to_json(cleaned: dict) -> dict:
    """Normalise cleaned filter data into JSON-storable, wizard-ready values.

    Dates become ``yyyy-mm-dd`` strings (what the portal's date inputs expect
    and what Playwright fills), and empty values are dropped.
    """
    import datetime as _dt

    out = {}
    for key, value in cleaned.items():
        if value in (None, '', False, []):
            continue
        if isinstance(value, (_dt.date, _dt.datetime)):
            out[key] = value.strftime('%Y-%m-%d')
        else:
            out[key] = value
    return out


class RawFiltersForm(forms.Form):
    """Fallback while the schema is unknown, and an escape hatch afterwards."""

    filters = forms.CharField(
        label='Filters (JSON)',
        required=False,
        widget=forms.Textarea(attrs={'rows': 8, 'spellcheck': 'false'}),
        help_text='e.g. {"country": "RO", "availability": "2026"}',
    )

    def clean_filters(self):
        raw = (self.cleaned_data['filters'] or '').strip()
        if not raw:
            return {}
        try:
            value = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise forms.ValidationError(f'Not valid JSON: {exc}') from exc
        if not isinstance(value, dict):
            raise forms.ValidationError('Filters must be a JSON object.')
        return value


class MessageTemplateForm(forms.ModelForm):
    class Meta:
        model = MessageTemplate
        fields = ['name', 'subject', 'body']
        widgets = {'body': forms.Textarea(attrs={'rows': 12})}


class GlobalSettingsForm(forms.ModelForm):
    class Meta:
        model = GlobalSettings
        fields = ['paused', 'hard_daily_ceiling']
