"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('ESC_DEBUG', '1') == '1'

# No usable key ships in this repo. Local development gets an obviously
# throwaway one; anything with DEBUG off must supply a real key through the
# environment, and is refused rather than silently signing cookies with a
# value the whole internet can read.
SECRET_KEY = os.environ.get('ESC_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'ESC_SECRET_KEY must be set when ESC_DEBUG=0. Generate one with: '
            '  python -c "from django.core.management.utils import '
            'get_random_secret_key as k; print(k())"'
        )
    SECRET_KEY = 'django-insecure-local-development-only-not-for-deployment'

# This tool is a single-user local application. It is never meant to be exposed
# to a network: the saved portal session it drives is a live admin credential.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'esc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # A run thread, the session heartbeat and a polling request all hit this
        # one file at once. WAL lets readers and the writer coexist, and the
        # busy timeout absorbs the rest instead of raising "database is locked".
        'OPTIONS': {
            'timeout': 20,
            'init_command': 'PRAGMA journal_mode=WAL;',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# European Solidarity Corps portal automation
# ---------------------------------------------------------------------------

ESC_BASE_URL = 'https://youth.europa.eu'

# The search page for a placement, formatted with the placement ("pass") id.
ESC_SEARCH_PATH = '/admin/esc/pass/{pass_id}/search_en'

# Hosts that mean "you are no longer logged in". Landing on any of these during
# a run raises SessionExpired rather than failing with a confusing parse error.
ESC_LOGIN_HOSTS = ('ecas.ec.europa.eu', 'webgate.ec.europa.eu')

# Saved Playwright storage state. This is a LIVE ADMIN SESSION for the portal —
# anyone holding this file can act as the organisation. Gitignored, kept out of
# the app package, and never rendered in the UI or written to a run log.
ESC_STORAGE_STATE = Path(
    os.environ.get('ESC_STORAGE_STATE', BASE_DIR / 'storage_state.json')
)

# Recon dumps. May contain candidate personal data, so also gitignored.
ESC_RECON_DIR = Path(os.environ.get('ESC_RECON_DIR', BASE_DIR / 'recon'))

# Run headless by default; esc_login always forces headed so the user can
# complete EU Login (including 2FA) by hand.
ESC_HEADLESS = os.environ.get('ESC_HEADLESS', '1') == '1'

# "Open login in same browser" uses the user's installed browser with a
# persistent profile that survives between logins, so sign-in is a one-time
# step. This profile dir holds live session cookies — gitignored.
ESC_BROWSER_PROFILE = Path(
    os.environ.get('ESC_BROWSER_PROFILE', BASE_DIR / '.browser_profile')
)
ESC_BROWSER_CHANNEL = os.environ.get('ESC_BROWSER_CHANNEL', 'chrome')

# How long to wait for EU Login to hand us back after a redirect. While the EU
# Login ticket is valid this is a silent round trip of a few seconds; only when
# it has expired does a credential form appear and the wait end early.
ESC_SSO_TIMEOUT = int(os.environ.get('ESC_SSO_TIMEOUT', '25'))

# Warn in the UI when the portal session cookie has this long or less to live.
ESC_SESSION_WARN_DAYS = int(os.environ.get('ESC_SESSION_WARN_DAYS', '2'))

# Keep-alive. The portal runs Drupal's autologout module, so an idle session is
# dropped well before its cookie expiry. A quiet page load every so often keeps
# it warm and re-exports the refreshed cookies, which is what turns "log in
# once" from a promise into a fact. Skipped whenever the browser is busy.
ESC_HEARTBEAT_ENABLED = os.environ.get('ESC_HEARTBEAT_ENABLED', '1') == '1'
ESC_HEARTBEAT_INTERVAL = int(os.environ.get('ESC_HEARTBEAT_INTERVAL', '900'))

# Default pacing. Deliberately slow: this contacts real people, and hammering
# the portal is the fastest way to get an organisation account suspended.
ESC_DEFAULT_MIN_DELAY = 8
ESC_DEFAULT_MAX_DELAY = 20
ESC_DEFAULT_PER_RUN_CAP = 25
ESC_DEFAULT_PER_DAY_CAP = 50

# Absolute ceiling. No SearchProfile may exceed this per day regardless of what
# is typed into the UI — a backstop against a fat-fingered 10000.
ESC_HARD_DAILY_CEILING = 200
